# Generated by Django 4.2 on 2023-05-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prensend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='brand',
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, upload_to='prensend/images/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='item',
            name='link',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
