# Generated by Django 4.2 on 2023-08-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prensend', '0003_item_category_item_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clueid', models.IntegerField(default=0)),
                ('userid', models.IntegerField(default=0)),
                ('cluename', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item_csv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(blank=True, max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('price', models.CharField(blank=True, max_length=30)),
                ('image', models.CharField(blank=True, max_length=300)),
                ('link', models.CharField(blank=True, max_length=300)),
                ('category', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.AddField(
            model_name='item',
            name='rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
